I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 7, in script call
    call LB_TEXAS_HOLDEM()
  File "game/z_Class_Poker.rpy", line 240, in script
    "The Turn is: [cards_open[3]['rank']] of [cards_open[3]['suit']]."
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 7, in script call
    call LB_TEXAS_HOLDEM()
  File "game/z_Class_Poker.rpy", line 240, in script
    "The Turn is: [cards_open[3]['rank']] of [cards_open[3]['suit']]."
  File "/Volumes/INTERNAL_NVM/Games/RenPy SDK/renpy/ast.py", line 2579, in execute
    Say.execute(self)
  File "/Volumes/INTERNAL_NVM/Games/RenPy SDK/renpy/ast.py", line 621, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/Volumes/INTERNAL_NVM/Games/RenPy SDK/renpy/exports/sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "/Volumes/INTERNAL_NVM/Games/RenPy SDK/renpy/character.py", line 1440, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "/Volumes/INTERNAL_NVM/Games/RenPy SDK/renpy/character.py", line 1354, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "/Volumes/INTERNAL_NVM/Games/RenPy SDK/renpy/character.py", line 1334, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "/Volumes/INTERNAL_NVM/Games/RenPy SDK/renpy/substitutions.py", line 373, in substitute
    s = interpolate(s, variables) # type: ignore
  File "/Volumes/INTERNAL_NVM/Games/RenPy SDK/renpy/substitutions.py", line 86, in interpolate
    raise e
  File "/Volumes/INTERNAL_NVM/Games/RenPy SDK/renpy/substitutions.py", line 78, in interpolate
    value = renpy.python.py_eval(code, {}, scope)
  File "/Volumes/INTERNAL_NVM/Games/RenPy SDK/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Volumes/INTERNAL_NVM/Games/RenPy SDK/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
  File "/Volumes/INTERNAL_NVM/Games/RenPy SDK/renpy/revertable.py", line 214, in __getitem__
    rv = list.__getitem__(self, index)
IndexError: list index out of range

macOS-15.5-arm64-arm-64bit arm64
Ren'Py 8.3.4.24120703
Poker 1.0
Sun Jun 15 00:57:14 2025
